### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by kalutro** [Truly-Modular/Modular-Item-API#37] opened 2024-04-12 16:49 UTC
**Describe the bug**
Right-clicking an item while it is in the workbench equips it, but does not remove it from the workbench.

**To Reproduce**
1. Place Workbench.
2. Place armor inside Workbench.
3. Right-click armor to equip. The armor will move to one of the armor slots to the right.
4. Close window and notice the armor is still rendering on the Workbench.
5. Be confused.
6. Open the Workbench and notice a copy of the armor in the Workbench.
7. Profit.

**Expected behavior**
I would not expect a copy of the armor.

**Screenshots**
![javaw_XlKVjP0irr](https://github.com/Truly-Modular/Modular-Item-API/assets/69569507/650452dd-3913-40f8-a655-cd56655e5044)

**Minecraft and Mod Version:**
Minecraft: 1.20.1
Forge: 47.2.0
Miapi: Truly-Modular-miapi-forge-1.1.14-1.20.1

**Full Mod List**
Architectury API (Fabric/Forge/NeoForge) [architectury-9.2.14-forge.jar]
Bookshelf [Bookshelf-Forge-1.20.1-20.1.10.jar]
Caelus API (Forge/NeoForge) [caelus-forge-3.1.0+1.20.jar]
Crate Delight (Forge) [cratedelight-1.0.8-1.20.1-forge.jar]
Create [create-1.20.1-0.5.1.f.jar]
Create Enchantment Industry [create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.c.jar]
Embeddium [embeddium-0.3.12+mc1.20.1.jar]
Embeddium++ [embeddiumplus-1.20.1-v1.2.7.jar]
EMI [emi-1.1.4+1.20.1+forge.jar]
Enchanting Infuser [Forge & Fabric] [EnchantingInfuser-v8.0.2-1.20.1-Forge.jar]
Enchantment Descriptions [EnchantmentDescriptions-Forge-1.20.1-17.0.14.jar]
Farmer's Delight [FarmersDelight-1.20.1-1.2.4.jar]
Fruits Delight [fruitsdelight-1.0.8.jar]
FTB Chunks (Forge) [ftb-chunks-forge-2001.2.7.jar]
FTB Library (Forge) [ftb-library-forge-2001.1.5.jar]
FTB Teams (Forge) [ftb-teams-forge-2001.2.0.jar]
Jade [Jade-1.20.1-forge-11.7.1.jar]
Jade Addons (Forge) [JadeAddons-1.20.1-forge-5.2.2.jar]
Nether's Delight [nethersdelight-1.20.1-4.0.jar]
Ocean's Delight [oceansdelight-1.0.2-1.20.jar]
Puzzles Lib [Forge & Fabric] [PuzzlesLib-v8.1.18-1.20.1-Forge.jar]
Quark [Quark-4.0-439.jar]
Sophisticated Backpacks [sophisticatedbackpacks-1.20.1-3.20.5.1039.jar]
Sophisticated Core [sophisticatedcore-1.20.1-0.6.18.597.jar]
Sophisticated Storage [sophisticatedstorage-1.20.1-0.10.20.778.jar]
TexTrue's Embeddium Options [textrues_embeddium_options-0.1.5+mc1.20.1.jar]
Truly Modular - Modular Item API [Truly-Modular-miapi-forge-1.1.14-1.20.1.jar]
Truly Modular: Archery [Truly-Modular-Archery-1.1-1.20.1-forge.jar]
Truly Modular: Armory [Truly-Modular-armory-forge-1.6-1.20.1.jar]
Truly Modular: Arsenal [Truly-Modular-arsenal-forge-1.7-1.20.1.jar]
Zeta [Zeta-1.0-16.jar]

**Ingame Logs**
n/a

**Additional context**
n/a

**Comment by Smartin-b** [comment] 2024-04-12 22:55
Hm. seems like a weird compat issue with quark(quark adds the right clickt o equip).
I dont quite understand the cause yet since otherwise taking the item out doesnt cause this issue

**Comment by Smartin-b** [comment] 2024-04-12 23:33
I now understand the issue, a fix will be in the enxt release

**Comment by Smartin-b** [comment] 2024-04-15 19:32
should be fixed in 1.1.15

**Closed by Smartin-b** 2024-04-15 19:32 UTC
Labels: fixedInNextRelease
